### ISSUE TITLE
`LocalWebMentionStorage` is not exported from package

### ISSUE THREAD

**Issue by paulrobertlloyd** [vandie/webmention-handler#18]
**Describe the bug**

In the readme, under the **Setup** heading it is suggested that example storage adapter can be imported as follows:

```js
import { localWebMentionStorage } from 'webmention-handler';

const storage = new LocalWebMentionStorage();
```

I’ve corrected a typo in #17 to update the import to reference `LocalWebMentionStorage` (capital ‘L’ as it is named in the module), but this function is not exported. It’s unclear from the documentation if this is intended to be exported or not, as later in the readme this function is linked to instead:

```md
An example storage handler can be found in the [local storage class](https://github.com/vandie/webmention-handler/blob/main/src/classes/local-web-mention-storage.class.ts).
```

**Comment by vandie** [comment]
It's an example, available in the codebase for reference but should not be used during implementation. The mongoDB handler is the one I use myself.

**Comment by paulrobertlloyd** [comment]
In which case, I think the readme should link to the example (as is done later in the readme) and not show an `import` from the module which isn’t available. Happy to create a PR for this change, if that’d help?

**Comment by vandie** [comment]
I guess it could be clearer but non convinced that linking would avoid this confusion.

**Comment by paulrobertlloyd** [comment]
Perhaps the mongo handler can be used as the example? Right now the readme says:

```md
To create instance of the example storage class, the following code can be used.
```

but the code shown can’t be used. This tripped me up as I was getting started, and it's the first line of code shown, so it's a bit of a trip hazard.

That said, I’ve been able to get a Webmention endpoint up and running in just a few hours, so thank you for all the work you’ve done on this package so far!

**Comment by vandie** [comment]
@paulrobertlloyd I understand the reasoning and why that tripped you up. My concern is that I don't want to push people towards using mongoDB.

**Comment by vandie** [comment]
For now, I've exported the example adapter. We can come back to this once we have an idea of how to improve this in a "non-opinionated" way.
